package view;

import javax.swing.*;
import java.awt.*;

import controller.CreateJobController;

public class CreateJobView implements UIView {
    private JPanel panelMain;
    private JTextArea jobDescriptionText;
    private JButton createJobButton;
    private JLabel createJobLabel;
    private JLabel jobTitleLabel;
    private JLabel jobDescriptionLabel;
    private JLabel locationLabel;
    private JLabel companyLabel;
    private JLabel jobCategoryLabel;
    private JLabel salaryRangeLabel;
    private JTextArea jobTitleText;
    private JComboBox salaryComboBox;
    private JComboBox categoryComboBox;
    private JComboBox locationComboBox;
    private JTextPane textPane1;
    private JTextArea locationText;
    private JTextArea companyText;
    private JTextArea jobTypeText;
    private JTextArea jobCategoryText;
    private JTextArea salaryRangeText;
    private CreateJobController controller;

    public CreateJobView(CreateJobController controller) {
        this.controller = controller;
        createJobButton.addActionListener((e) -> {
            String company = getCompanyText().toString();
            String description = getJobDescriptionText().getText();
            String jobType = getJobTypeText().getText();
            String title = getJobTitleText().getText();
            controller.doCreateJob(title, description, jobType, company);
        });
    }

    public JComboBox getSalaryComboBox() {
        return salaryComboBox;
    }

    public void setSalaryComboBox(JComboBox salaryComboBox) {
        this.salaryComboBox = salaryComboBox;
    }

    public JComboBox getCategoryComboBox() {
        return categoryComboBox;
    }

    public void setCategoryComboBox(JComboBox categoryComboBox) {
        this.categoryComboBox = categoryComboBox;
    }

    public JComboBox getLocationComboBox() {
        return locationComboBox;
    }

    public void setLocationComboBox(JComboBox locationComboBox) {
        this.locationComboBox = locationComboBox;
    }

    @Override
    public JComponent getUIView() {
        return panelMain;
    }

    public JTextArea getJobDescriptionText() {
        return jobDescriptionText;
    }

    public JTextArea getJobTitleText() {
        return jobTitleText;
    }

    public JTextArea getLocationText() {
        return locationText;
    }

    public JTextArea getCompanyText() {
        return companyText;
    }

    public JTextArea getJobTypeText() {
        return jobTypeText;
    }

    public JTextArea getJobCategoryText() {
        return jobCategoryText;
    }

    public JTextArea getSalaryRangeText() {
        return salaryRangeText;
    }

    public static void main(String[] args) {
        CreateJobView myCreateJobView = new CreateJobView(null);
        ViewHelper.showStandaloneFrame(myCreateJobView);
    }
}
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!